name: ASP.NET Core CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-16.04
   
    name: Setup Dotnet
    steps:
      - uses: actions/checkout@master
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.401
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.0.100-preview8-013656
      
      - run: dotnet build && dotnet test 


  
